// examples/next/pages/index.tsx
export default function Home() {
  return (
    <form
      onSubmit={async (evt) => {
        evt.preventDefault();

        const target = evt.currentTarget;

        const form = new FormData(target);
        await fetch("/api/enqueueGreeting", {
          method: "POST",
          body: JSON.stringify({
            name: form.get("name"),
          }),
          headers: {
            "Content-Type": "application/json",
          },
        });

        target.reset();
      }}
    >
      <h1>Enqueue a Greeting!</h1>
      <label>
        Name
        <input name="name" />
      </label>

      <button type="submit">Enqueue</button>
    </form>
  );
}

// examples/nuxt/pages/index.vue
<template>
  <form v-on:submit.prevent="sendMessage">
    <h1>
      Send a greeting!
    </h1>

    <label>
      Name
      <input required name="name" v-model="name" />
    </label>

    <button type="submit">Enqueue</button>
  </form>
</template>

<script>
export default {
  data: () => ({
    name: ""
  }),
  methods: {
    sendMessage() {
      fetch("/api/enqueueGreeting", { method: "POST", body: this.name })
      this.name = ""
    }
  }
};
</script>
